<?php
$city = array();

$city['hot'] = array(
'AB' =>array('beijing'=>'北京','guangzhou'=>'广州','shanghai'=>'上海','shenzhen'=>'深圳','hebei'=>'河北','shanxi'=>'山西','neimenggu'=>'内蒙古','liaoning'=>'辽宁','jilin'=>'吉林','heilongjiang'=>'黑龙江','jiangsu'=>'江苏','zhejiang'=>'浙江','anhui'=>'安徽','fujian'=>'福建','jiangxi'=>'江西','shandong'=>'山东','henan'=>'河南','hubei'=>'湖北','hunan'=>'湖南','guagndong'=>'广东','guangxi'=>'广西','hainan'=>'海南','sichuan'=>'四川','guizhou'=>'贵州','yunnan'=>'云南','xizang'=>'西藏','shanxi'=>'陕西','gansu'=>'甘肃','qinghai'=>'青海','ningxia'=>'宁夏','xinjiang'=>'新疆'),
'AC' =>array('hangzhou'=>'杭州','shenyang'=>'沈阳','wuhan'=>'武汉','xian'=>'西安','nanjing'=>'南京','tianjin'=>'天津','taiyuan'=>'太原','changchuen'=>'长春','heifei'=>'合肥','nanchang'=>'南昌','zhengzhou'=>'郑州','changsha'=>'长沙','haikou'=>'海口','guiyang'=>'贵阳','xining'=>'西宁','huhehaote'=>'呼和浩特','lasa'=>'拉萨','wulumuqi'=>'乌鲁木齐','shijiazhuang'=>'石家庄','haerbin'=>'哈尔滨','fuzhou'=>'福州','jinan'=>'济南','chengdu'=>'成都','kunming'=>'昆明','lanzhou'=>'兰州','nanning'=>'南宁','yinchuan'=>'银川','chongqing'=>'重庆','suzhou'=>'苏州','dalian'=>'大连','ningbo'=>'宁波','qingdao'=>'青岛','wuxi'=>'无锡','xiamen'=>'厦门','changzhou'=>'常州','fuzhou'=>'福州','dongguan'=>'东莞','wenzhou'=>'温州','foshan'=>'佛山',)
	);

//所有城市
$city['list'] = array(
'A' => array('aershan'=>'阿尔山','akesu'=>'阿克苏','alaer'=>'阿拉尔','aletai'=>'阿勒泰','anda'=>'安达','anguo'=>'安国','ankang'=>'安康','anlu'=>'安陆','anning'=>'安宁','anqing'=>'安庆','anqiu'=>'安丘','anshan'=>'鞍山','anshun'=>'安顺','anyang'=>'安阳','atushi'=>'阿图什','alashanzuoqi'=>'阿拉善左旗','ali'=>'阿里'),	
'B' => array('baise'=>'百色','baishan'=>'白山','baiyin'=>'白银','bangbu'=>'蚌埠','baoding'=>'保定','baoji'=>'宝鸡','baoshan'=>'保山','baotou'=>'包头','bazhong'=>'巴中','bazhou'=>'霸州','beian'=>'北安','beihai'=>'北海','beiliu'=>'北流','beining'=>'北宁','beipiao'=>'北票','benxi'=>'本溪','bijie'=>'毕节','binzhou'=>'滨州','bole'=>'博乐','botou'=>'泊头','haozhou'=>'亳州'),
'C' => array('cenxi'=>'岑溪','changde'=>'常德','changdu'=>'昌都','changge'=>'长葛','changji'=>'昌吉','changle'=>'长乐','changning'=>'常宁','changshu'=>'常熟','changyi'=>'昌邑','changzhi'=>'长治','chaohu'=>'巢湖','chaoyang'=>'朝阳','chaozhou'=>'潮州','chegnde'=>'承德','chengxian'=>'成县','chenzhou'=>'郴州','chibi'=>'赤壁','chifeng'=>'赤峰','chishui'=>'赤水','chizhou'=>'池州','chongzhou'=>'崇州','chongzuo'=>'崇左','chuxiong'=>'楚雄','chuzhou'=>'滁州','cixi'=>'慈溪','conghua'=>'从化'),
'D' => array('dafeng'=>'大丰','dali'=>'大理','dadong'=>'丹东','dangyang'=>'当阳','dajiangkou'=>'丹江口','danyang'=>'丹阳','danzhou'=>'儋州','daqing'=>'大庆','dashiqiao'=>'大石桥','datong'=>'大同','daye'=>'大冶','dazhou'=>'达州','dehui'=>'德惠','delingha'=>'德令哈','dengfeng'=>'登封','dengta'=>'灯塔','dengzhou'=>'邓州','dexing'=>'德兴','deyang'=>'德阳','dezhou'=>'德州','diaobingshan'=>'调兵山','dingxi'=>'定西','dingzhou'=>'定州','dongfang'=>'东方','donggang'=>'东港','dongtai'=>'东台','dongxing'=>'东兴','dongyang'=>'东阳','dongying'=>'东营','dujiangyan'=>'都江堰','dunhua'=>'敦化','dunhuang'=>'敦煌','duyun'=>'都匀'),
'E' => array('eerguna'=>'额尔古纳','emeishan'=>'峨眉山','enping'=>'恩平','enshi'=>'恩施','erlianhaote'=>'二连浩特','ezhou'=>'鄂州'),
'F' => array('fengcheng'=>'丰城','feicheng'=>'肥城','fengcheng'=>'凤城','fenghua'=>'奉化','fengzhen'=>'丰镇','fenyang'=>'汾阳','fuan'=>'福安','fuding'=>'福鼎','fujin'=>'富锦','fukang'=>'阜康','fuqing'=>'福清','fuquan'=>'福泉','fushun'=>'抚顺','fuxin'=>'阜新','fuyang'=>'阜阳','fuyang'=>'富阳','fuzhou'=>'抚州'),
'G' => array('gaizhou'=>'盖州','ganzhou'=>'赣州','gaoan'=>'高安','gaobeidian'=>'高碑店','qiancheng'=>'藁城','gaomi'=>'高密','gaoping'=>'高平','gaoyao'=>'高要','gaoyou'=>'高邮',
			'gaozhou'=>'高州','grmu'=>'格尔木','gejiu'=>'个旧','genhe'=>'跟和','gonghe'=>'共和','gongyi'=>'巩义','gongzhuling'=>'公主岭','guangan'=>'广安','guanghan'=>'广汉','guangshui'=>'广水','guangyuan'=>'广元','guigang'=>'贵港','guilin'=>'桂林','guiping'=>'桂平','guixi'=>'贵溪','gujiao'=>'古交','guyuan'=>'固原'),
'H' => array('haicheng'=>'海城','hailin'=>'海林','hailun'=>'海伦','haimen'=>'海门','haining'=>'海宁','haiyan'=>'海晏','haiyang'=>'海阳','hami'=>'哈密','hancheng'=>'韩城','hanchuang'=>'汉川','handan'=>'邯郸',
			'hebi'=>'鹤壁','hechi'=>'河池','hegang'=>'鹤岗','heihe'=>'黑河','hejian'=>'河间','hejin'=>'河津','helong'=>'合龙','hengshui'=>'衡水','hengyan'=>'衡阳','heshan'=>'合山','hetian'=>'和田','heyuan'=>'河源','heze'=>'菏泽','hezhou'=>'贺州','hezhou'=>'合作','honghu'=>'洪湖','hongjiang'=>'洪江','houma'=>'侯马','heshan'=>'贺山','huadian'=>'桦甸','huaian'=>'淮安','huaibei'=>'淮北','huaihua'=>'怀化','huainan'=>'淮南',
			'huanggang'=>'黄冈','huanghua'=>'黄骅','huangshan'=>'黄山','huangshi'=>'黄 石','huayin'=>'华阴','huaying'=>'华蓥','huazhou'=>'化州',
			'huixian'=>'辉县','huizhou'=>'惠州','hulin'=>'虎林','huloudao'=>'葫岛','hulunbeier'=>'呼伦贝尔','huichun'=>'珲春','huolinguole'=>'霍林郭勒','huozhou'=>'霍州','huzhou'=>'湖州'),
'J' => array('jiagedaqi'=>'加格达奇','jiamusi'=>'佳木斯','jian'=>'集安','jiande'=>'建 德','jiangdu'=>'江都','jiangmen'=>'江门','jiangshan'=>'江山','jiangyan'=>'姜堰','jiangyin'=>'江阴',
			'jiangyou'=>'江油','jiano'=>'建瓯','jiaonan'=>'胶南','jiaozhou'=>'胶州','jiaozuo'=>'焦作','jiaxing'=>'嘉兴','jiayuguan'=>'嘉峪关',
			'jieshou'=>'界首','jiexiu'=>'介休','jieyang'=>'揭阳','jilin'=>'吉林','jimo'=>'即墨','jingdezhen'=>'景德镇','jinggangshan'=>'井冈山',
			'jinghong'=>'景洪','jingjiang'=>'靖江','jingmen'=>'荆门','jingzhou'=>'荆州','jinhua'=>'金华','jining'=>'集宁','jinjiang'=>'晋        江','jingshi'=>'津市','jingtan'=>'金坛','jinzhou'=>'晋中','jingzhou'=>'锦州','jishou'=>'吉        首','jiujiang'=>'九江','jiuquan'=>'酒泉','jiutai'=>'九台','jixi'=>'鸡西','jiyuan'=>'济  源','jizhou'=>'冀州','jining'=>'济宁','jurong'=>'句容','jianyang'=>'简阳','jinzhou'=>'晋州'),
'K' => array('kaili'=>'凯里','kaiping'=>'开平','kaiyuan'=>'开原','kangding'=>'康定','kashi'=>'喀什','kelamayi'=>'克拉玛依','kuerle'=>'库尔勒','kuitun'=>'奎屯','kunshan'=>'昆山','kaiyuan'=>'开远'),
'L' => array('laiwu'=>'莱芜','laixi'=>'莱西','laiyang'=>'莱阳','laizhou'=>'莱州','langfang'=>'廊坊','langzhong'=>'阆中','lanxi'=>'兰溪','laohekou'=>'老河口','lechang'=>'乐昌','leiyang'=>'耒阳','leizhou'=>'雷州','leling'=>'乐陵','lengshuijiang'=>'冷水江','leping'=>'乐平','leqing'=>'乐清','leshan'=>'乐山','lianjiang'=>'廉江','lianyuan'=>'涟源','lianyungang'=>'连云港','lianzhou'=>'连州',
			'liaocheng'=>'聊城','liaoyang'=>'辽阳','liaoyuan'=>'辽源','lichuan'=>'利川','lijiang'=>'丽江','liling'=>'醴陵','linan'=>'临安','lincang'=>'临沧','linfen'=>'临汾','lingbao'=>'灵宝','linghai'=>'凌海','lingyuan'=>'凌源','linhai'=>'临海','linhe'=>'临河','linjiang'=>'临江','linqing'=>'临清','linxia'=>'临夏','linxiang'=>'临湘','linyi'=>'临沂','linzhi'=>'林芝','linzhou'=>'林州','lishi'=>'离石','lishui'=>'丽水','liuan'=>'六安','liupanshui'=>'六盘水','liuyang'=>'浏阳','liuzhou'=>'柳州','liyang'=>'溧阳','longhai'=>'龙海','longjing'=>'龙井','longkou'=>'龙口','longquan'=>'龙泉','longyan'=>'龙岩','loudi'=>'娄底','lucheng'=>'潞城','lufeng'=>'陆丰','luoding'=>'罗定','luohe'=>'漯河','luoyang'=>'洛阳','luquan'=>'鹿泉','lushui'=>'泸水','luxi'=>'潞西','luzhou'=>'泸州'),
'M' => array('macheng'=>'麻城','maerkang'=>'马尔康','manzhouli'=>'满洲里','maoming'=>'茂名','maqin'=>'玛沁','meihekou'=>'梅河口','meishan'=>'眉山','meizhou'=>'梅州','mengzhou'=>'孟州','mengzi'=>'蒙自','mianyang'=>'绵阳','mianzhu'=>'绵竹','miluo'=>'汨罗','mingguang'=>'明光','miquan'=>'米泉','mishan'=>'密山','mudanjiang'=>'牡丹江','muleng'=>'穆棱'),
'R' => array('renqiu'=>'任丘','rikaze'=>'日喀则','rizhao'=>'日照','rongcheng'=>'荣成','rugao'=>'如皋','ruian'=>'瑞安','ruichang'=>'瑞昌','ruijin'=>'瑞金','rushan'=>'乳山','ruzhou'=>'汝州'),
'S' => array('sanmenxia'=>'三门峡','sanming'=>'三明','sanya'=>'三亚','sanhe'=>'沙河','shangluo'=>'商洛','shangqiu'=>'商丘','shangrao'=>'上饶','shangyu'=>'上虞','尚志'=>'尚志','shanto'=>'汕头','shanwei'=>'汕尾','shaoguan'=>'韶关','shaoshan'=>'韶山','shaowu'=>'邵武','shaoxing'=>'绍兴','shaoyang'=>'邵阳','shengzhou'=>'嵊州','zhenzhou'=>'深州','shenfang'=>'深邡','shihezi'=>'石河子','shishi'=>'石狮','shishou'=>'石首','shiyan'=>'十堰','shizuishan'=>'石嘴山','shouguang'=>'寿光','shuangcheng'=>'双城','shuangliao'=>'双辽','shuangyashan'=>'双鸭山','shulan'=>'舒兰','shuozhou'=>'朔州','sihui'=>'四会','sihui'=>'四平','songyuan'=>'松原','songzi'=>'松滋','suifenhe'=>'绥芬河','suihua'=>'绥化','suining'=>'遂宁','suizhou'=>'随州','suqian'=>'宿迁','szhou'=>'宿州'),
'T' => array('taian'=>'泰安','taicang'=>'太仓','taishan'=>'台山','taixing'=>'泰兴','tzhou'=>'泰州','tangshan'=>'唐山','taonan'=>'洮南','tengzhou'=>'滕州','tianchang'=>'天长','tianmen'=>'天门','tianshui'=>'天水','teili'=>'铁力','tieling'=>'铁岭','tongcheng'=>'桐城','tongchuan'=>'铜川','tonghua'=>'通化','tongjiang'=>'同江','tongliao'=>'通辽','tongling'=>'铜陵','tongren'=>'铜仁','tongxiang'=>'桐乡','tongzhou'=>'通州','tongren'=>'同仁','tulufan'=>'吐鲁番','tumen'=>'图们','tumushuke'=>'图木舒克','taizhou'=>'台州',),
'P' => array('panshi'=>'磐石','panzhihua'=>'攀枝花','penglai'=>'蓬莱','pengzhou'=>'彭州','pingan'=>'平安','pingdingshan'=>'平顶山','pingdu'=>'平度','pinghu'=>'平湖','pingliang'=>'平凉','pingxiang'=>'凭祥','pizhou'=>'邳州','puer'=>'普洱','pulandian'=>'普兰店','puning'=>'普宁','putian'=>'莆田','puyang'=>'濮阳','px'=>'萍乡'),
'Q' => array('qianjiang'=>'潜江','qidong'=>'启东','qingtongxia'=>'青铜峡','qingyang'=>'庆阳','qingyuan'=>'清远','qingzhen'=>'清镇','qingzhou'=>'青州','qianhuangdao'=>'秦皇岛','qinyang'=>'沁阳','qinzhou'=>'钦州','qionghai'=>'琼海','qionglai'=>'邛崃','qiqihaer'=>'齐齐哈尔','qitaihe'=>'七台河','qixia'=>'栖霞','quanzhou'=>'泉州','qujing'=>'曲靖','quzhou'=>'衢州'),
'W' => array('wanning'=>'万宁','wanyuan'=>'万源','weifang'=>'潍坊','weihai'=>'威海','weihui'=>'卫辉','weinan'=>'渭南','wenchang'=>'文昌','wendeng'=>'文登','wenling'=>'温岭','wenshan'=>'文山','wg'=>'舞钢','wuan'=>'武安','wuchang'=>'五常','wuchuan'=>'吴川','wudalianchi'=>'五大连池','wugang'=>'武冈','wuhai'=>'乌海','wuhu'=>'芜湖','wujiang'=>'吴江','wujiaqu'=>'五家渠','wulanhaote'=>'乌兰浩特','wusu'=>'乌苏','wuwei'=>'武威','wuxue'=>'武穴','wuyishan'=>'武夷山','wuzhishan'=>'五指山','wuzhong'=>'吴忠','wuzhou'=>'梧州'),
'X' => array('xiangcheng'=>'项城','xgll'=>'香格里拉','xiangtan'=>'湘潭','xiangxian'=>'湘 乡','xiangyang'=>'襄阳','xianning'=>'咸宁','xiantao'=>'仙桃','xianyang'=>'咸阳','xiaogan'=>'孝感','xiaoyi'=>'孝 义','xichang'=>'西昌','xilinghaote'=>'锡林浩特','xiangcheng'=>'兴城','xinghua'=>'兴化','xintai'=>'兴宁','xingping'=>'兴 平','xintai'=>'邢台','xingyang'=>'荥阳','xingyi'=>'兴义','xingji'=>'辛集','xinle'=>'新乐','xinmi'=>'新 密','xinmin'=>'新民','xintai'=>'新泰','xinxiang'=>'新乡','xinyang'=>'信阳','xinyi'=>'信宜','xinyu'=>'新余','xinzheng'=>'新郑','xinzhou'=>'忻州','xuancheng'=>'宣城','xuanwei'=>'宣威','xvchang'=>'许昌','xvzhou'=>'徐 州','xinyi'=>'新沂'),
'Z' => array('zaozhuang'=>'枣庄','zengcheng'=>'增城','zhalantun'=>'扎兰屯','zhangjiajie'=>'张家界','zhangjiakou'=>'张家口','zhangping'=>'漳平','zhangqiu'=>'章丘','zhangshu'=>'樟树','zhangye'=>'张掖','zhangzhou'=>'漳州','zhanjiang'=>'湛江','zhaodong'=>'肇东','zhaoqing'=>'肇庆','zhaotong'=>'昭通','zhaoyuan'=>'招远','zhenjiang'=>'镇江','zhijiang'=>'枝江','zhongshan'=>'中山','zhongxiang'=>'钟祥','zhoukou'=>'周口','zhoushan'=>'舟山','zhuanghe'=>'庄河','zhucheng'=>'诸城','zhuhai'=>'珠海','zhuji'=>'诸暨','zhumadian'=>'驻马店','zhuzhou'=>'涿州','zhuuzhou'=>'株洲','zibo'=>'淄博','zigong'=>'自贡','zixing'=>'资兴','ziyang'=>'资阳','zoucheng'=>'邹城','zunhua'=>'遵化','zunyi'=>'遵义'),
'Y' => array('yakeshi'=>'牙克石','yanan'=>'延安','yancheng'=>'盐城','yangchun'=>'阳春','yangjiang'=>'阳江','yangquan'=>'阳泉','yangzhong'=>'扬中','yangzhou'=>'扬州','yanzhou '=>'兖州','yanji'=>'延吉','yanshi'=>'偃师','yantai'=>'烟台','yichun'=>'伊春','yibin'=>'宜宾','yichang'=>'宜昌','yicheng'=>'宜城','yichun'=>'宜春','yidu'=>'宜都','yima'=>'义马','yingcheng'=>'应城','yingde'=>'英德','yingkou'=>'营口','yingtan'=>'鹰潭','yining'=>'伊宁','yiwu'=>'义乌','yixing'=>'宜兴','yiyang'=>'益阳','yizheng'=>'仪征','yizhou'=>'宜州','yulin'=>'榆林','yongan'=>'永安','yongcheng'=>'永城','yongji'=>'永济','yongkang'=>'永康','yongzhou'=>'永州','yushu'=>'玉树','yuanjiang'=>'沅江','yuanping'=>'原平','yucheng'=>'禹城','yueyang'=>'岳阳','yulin'=>'玉林','yumen'=>'玉门','yuncheng'=>'运城','yunfu'=>'云浮','yushu'=>'榆树','yuxi'=>'玉溪','yuyao'=>'余姚','yuzhou'=>'禹州'),	
);